elements = [
    {"id": 1, "symbol": "H",  "name": "Водород", "description": "Самый легкий элемент, газ без цвета и запаха."},
    {"id": 2, "symbol": "He", "name": "Гелий", "description": "Инертный газ, второй по распространенности во Вселенной."},
    {"id": 3, "symbol": "Li", "name": "Литий", "description": "Щелочной металл, используется в аккумуляторах."},
    {"id": 4, "symbol": "Be", "name": "Бериллий", "description": "Щелочноземельный металл, токсичен."},
    {"id": 5, "symbol": "B",  "name": "Бор", "description": "Полуметалл, используется в сплавах."},
    {"id": 6, "symbol": "C",  "name": "Углерод", "description": "Основной элемент органической химии."},
    {"id": 7, "symbol": "N",  "name": "Азот", "description": "78% атмосферы Земли."},
    {"id": 8, "symbol": "O",  "name": "Кислород", "description": "Необходим для дыхания большинства организмов."},
    {"id": 9, "symbol": "F",  "name": "Фтор", "description": "Очень реактивный газ, сильный окислитель."},
    {"id": 10, "symbol": "Ne", "name": "Неон", "description": "Инертный газ, используется в лампах."},
    {"id": 11, "symbol": "Na", "name": "Натрий", "description": "Щелочной металл, высокореактивен."},
    {"id": 12, "symbol": "Mg", "name": "Магний", "description": "Легкий металл, используется в сплавах."},
    {"id": 13, "symbol": "Al", "name": "Алюминий", "description": "Легкий металл, широко используется."},
    {"id": 14, "symbol": "Si", "name": "Кремний", "description": "Основной элемент электроники."},
    {"id": 15, "symbol": "P",  "name": "Фосфор", "description": "Элемент, необходимый для жизни."},
    {"id": 16, "symbol": "S",  "name": "Сера", "description": "Неметалл, используется в химии."},
    {"id": 17, "symbol": "Cl", "name": "Хлор", "description": "Газ с резким запахом, окислитель."},
    {"id": 18, "symbol": "Ar", "name": "Аргон", "description": "Инертный газ, 1% атмосферы."},
    {"id": 19, "symbol": "K",  "name": "Калий", "description": "Щелочной металл, биологически важен."},
    {"id": 20, "symbol": "Ca", "name": "Кальций", "description": "Основной элемент костей."},
    {"id": 21, "symbol": "Sc", "name": "Скандий", "description": "Легкий металл, используется в авиации."},
    {"id": 22, "symbol": "Ti", "name": "Титан", "description": "Прочный и легкий металл."},
    {"id": 23, "symbol": "V",  "name": "Ванадий", "description": "Используется в легированных сталях."},
    {"id": 24, "symbol": "Cr", "name": "Хром", "description": "Твердый металл, устойчив к коррозии."},
    {"id": 25, "symbol": "Mn", "name": "Марганец", "description": "Используется в сталях."},
    {"id": 26, "symbol": "Fe", "name": "Железо", "description": "Основа сталей, важный элемент."},
    {"id": 27, "symbol": "Co", "name": "Кобальт", "description": "Используется в магнитах."},
    {"id": 28, "symbol": "Ni", "name": "Никель", "description": "Коррозионностойкий металл."},
    {"id": 29, "symbol": "Cu", "name": "Медь", "description": "Хороший проводник электричества."},
    {"id": 30, "symbol": "Zn", "name": "Цинк", "description": "Используется для оцинковки."},
    {"id": 31, "symbol": "Ga", "name": "Галлий", "description": "Металл, плавящийся на руках."},
    {"id": 32, "symbol": "Ge", "name": "Германий", "description": "Полупроводник."},
    {"id": 33, "symbol": "As", "name": "Мышьяк", "description": "Токсичный полуметалл."},
    {"id": 34, "symbol": "Se", "name": "Селен", "description": "Используется в электронике."},
    {"id": 35, "symbol": "Br", "name": "Бром", "description": "Жидкий галоген."},
    {"id": 36, "symbol": "Kr", "name": "Криптон", "description": "Инертный газ."},
    {"id": 37, "symbol": "Rb", "name": "Рубидий", "description": "Щелочной металл."},
    {"id": 38, "symbol": "Sr", "name": "Стронций", "description": "Используется в пиротехнике."},
    {"id": 39, "symbol": "Y",  "name": "Иттрий", "description": "Используется в лазерах."},
    {"id": 40, "symbol": "Zr", "name": "Цирконий", "description": "Стойкий металл."},
    {"id": 41, "symbol": "Nb", "name": "Ниобий", "description": "Сверхпроводники."},
    {"id": 42, "symbol": "Mo", "name": "Молибден", "description": "Жаропрочный металл."},
    {"id": 43, "symbol": "Tc", "name": "Технеций", "description": "Радиоактивный элемент."},
    {"id": 44, "symbol": "Ru", "name": "Рутений", "description": "Используется в каталитике."},
    {"id": 45, "symbol": "Rh", "name": "Родий", "description": "Драгоценный металл."},
    {"id": 46, "symbol": "Pd", "name": "Палладий", "description": "Катализаторы, электроника."},
    {"id": 47, "symbol": "Ag", "name": "Серебро", "description": "Ценный металл, проводник."},
    {"id": 48, "symbol": "Cd", "name": "Кадмий", "description": "Токсичный металл."},
    {"id": 49, "symbol": "In", "name": "Индий", "description": "Используется в мониторах."},
    {"id": 50, "symbol": "Sn", "name": "Олово", "description": "Паяльные сплавы."},
    {"id": 51, "symbol": "Sb", "name": "Сурьма", "description": "Полуметалл."},
    {"id": 52, "symbol": "Te", "name": "Теллур", "description": "Редкий полуметалл."},
    {"id": 53, "symbol": "I",  "name": "Йод", "description": "Элемент, важный для здоровья."},
    {"id": 54, "symbol": "Xe", "name": "Ксенон", "description": "Инертный газ."},
    {"id": 55, "symbol": "Cs", "name": "Цезий", "description": "Очень мягкий щелочной металл."},
    {"id": 56, "symbol": "Ba", "name": "Барий", "description": "Используется в рентгенографии."},
    {"id": 57, "symbol": "La", "name": "Лантан", "description": "Редкоземельный металл."},
    {"id": 57, "symbol": "La", "name": "Лантан", "description": "Первый в ряду лантаноидов."},
    {"id": 58, "symbol": "Ce", "name": "Церий", "description": "Используется в зажигалках и стеклах."},
    {"id": 59, "symbol": "Pr", "name": "Празеодим", "description": "Используется в магнитах."},
    {"id": 60, "symbol": "Nd", "name": "Неодим", "description": "Сильные постоянные магниты."},
    {"id": 61, "symbol": "Pm", "name": "Прометий", "description": "Редкий радиоактивный элемент."},
    {"id": 62, "symbol": "Sm", "name": "Самарий", "description": "Магнитные материалы."},
    {"id": 63, "symbol": "Eu", "name": "Европий", "description": "Используется в экранах."},
    {"id": 64, "symbol": "Gd", "name": "Гадолиний", "description": "МРТ-контраст."},
    {"id": 65, "symbol": "Tb", "name": "Тербий", "description": "Фосфоры, электроника."},
    {"id": 66, "symbol": "Dy", "name": "Диспрозий", "description": "Жаропрочные магниты."},
    {"id": 67, "symbol": "Ho", "name": "Гольмий", "description": "Высокие магнитные свойства."},
    {"id": 68, "symbol": "Er", "name": "Эрбий", "description": "Оптоволоконные усилители."},
    {"id": 69, "symbol": "Tm", "name": "Тулий", "description": "Редкий и дорогой элемент."},
    {"id": 70, "symbol": "Yb", "name": "Иттербий", "description": "Используется в лазерах."},
    {"id": 71, "symbol": "Lu", "name": "Лютеций", "description": "Самый тяжелый лантаноид."},

    {"id": 72, "symbol": "Hf", "name": "Гафний", "description": "Используется в ядерных реакторах."},
    {"id": 73, "symbol": "Ta", "name": "Тантал", "description": "Устойчив к коррозии."},
    {"id": 74, "symbol": "W",  "name": "Вольфрам", "description": "Самая высокая температура плавления."},
    {"id": 75, "symbol": "Re", "name": "Рений", "description": "Редкий металл, катализаторы."},
    {"id": 76, "symbol": "Os", "name": "Осмий", "description": "Самый плотный элемент."},
    {"id": 77, "symbol": "Ir", "name": "Иридий", "description": "Очень коррозионностойкий."},
    {"id": 78, "symbol": "Pt", "name": "Платина", "description": "Драгоценный металл, катализаторы."},
    {"id": 79, "symbol": "Au", "name": "Золото", "description": "Благородный металл."},
    {"id": 80, "symbol": "Hg", "name": "Ртуть", "description": "Жидкий металл."},

    {"id": 81, "symbol": "Tl", "name": "Таллий", "description": "Токсичный металл."},
    {"id": 82, "symbol": "Pb", "name": "Свинец", "description": "Тяжелый металл, токсичен."},
    {"id": 83, "symbol": "Bi", "name": "Висмут", "description": "Нетоксичный тяжелый металл."},
    {"id": 84, "symbol": "Po", "name": "Полоний", "description": "Высокорадиоактивен."},
    {"id": 85, "symbol": "At", "name": "Астат", "description": "Крайне редкий элемент."},
    {"id": 86, "symbol": "Rn", "name": "Радон", "description": "Радиоактивный инертный газ."},

    {"id": 87, "symbol": "Fr", "name": "Франций", "description": "Очень радиоактивный щелочной металл."},
    {"id": 88, "symbol": "Ra", "name": "Радий", "description": "Использовался в люминесцентных красках."},
    {"id": 89, "symbol": "Ac", "name": "Актиний", "description": "Радиоактивный металл."},

    {"id": 90, "symbol": "Th", "name": "Торий", "description": "Используется в ядерной энергетике."},
    {"id": 91, "symbol": "Pa", "name": "Протактиний", "description": "Редкий радиоактивный элемент."},
    {"id": 92, "symbol": "U",  "name": "Уран", "description": "Основной элемент ядерного топлива."},
    {"id": 93, "symbol": "Np", "name": "Нептуний", "description": "Радиоактивный трансурановый."},
    {"id": 94, "symbol": "Pu", "name": "Плутоний", "description": "Ядерное топливо и оружейный материал."},
    {"id": 95, "symbol": "Am", "name": "Америций", "description": "Датчики дыма."},
    {"id": 96, "symbol": "Cm", "name": "Кюрий", "description": "Радиоактивный металл."},
    {"id": 97, "symbol": "Bk", "name": "Берклий", "description": "Лабораторный элемент."},
    {"id": 98, "symbol": "Cf", "name": "Калифорний", "description": "Источник нейтронов."},
    {"id": 99, "symbol": "Es", "name": "Эйнштейний", "description": "Синтетический элемент."},
    {"id": 100,"symbol": "Fm", "name": "Фермий", "description": "Редкий трансурановый."},
    {"id": 101,"symbol": "Md", "name": "Менделевий", "description": "Назван в честь Менделеева."},
    {"id": 102,"symbol": "No", "name": "Нобелий", "description": "Редкий синтетический."},
    {"id": 103,"symbol": "Lr", "name": "Лоуренсий", "description": "Актиноид."},

    {"id": 104,"symbol": "Rf", "name": "Резерфордий", "description": "Транзактиноид."},
    {"id": 105,"symbol": "Db", "name": "Дубний", "description": "Назван в честь Дубны."},
    {"id": 106,"symbol": "Sg", "name": "Сиборгий", "description": "Синтетический элемент."},
    {"id": 107,"symbol": "Bh", "name": "Борий", "description": "Синтетический элемент."},
    {"id": 108,"symbol": "Hs", "name": "Хассий", "description": "Тяжелый синтетический."},
    {"id": 109,"symbol": "Mt", "name": "Мейтнерий", "description": "Назван в честь Лизы Мейтнер."},
    {"id": 110,"symbol": "Ds", "name": "Дармштадтий", "description": "Синтезирован в Дармштадте."},
    {"id": 111,"symbol": "Rg", "name": "Рентгений", "description": "Назван в честь Рентгена."},
    {"id": 112,"symbol": "Cn", "name": "Коперникий", "description": "В честь Коперника."},
    {"id": 113,"symbol": "Nh", "name": "Нихоний", "description": "Открыт в Японии."},
    {"id": 114,"symbol": "Fl", "name": "Флеровий", "description": "В честь Флерова."},
    {"id": 115,"symbol": "Mc", "name": "Московий", "description": "В честь Московской области."},
    {"id": 116,"symbol": "Lv", "name": "Ливерморий", "description": "Национальная лаборатория Ливермора."},
    {"id": 117,"symbol": "Ts", "name": "Теннессин", "description": "В честь Теннесси."},
    {"id": 118,"symbol": "Og", "name": "Оганесон", "description": "В честь Юрия Оганесяна."}
]

